### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/account-financial-reporting#125]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [x] account_journal_report_xls > account_journal_report - By @mreficent - #298 
- [ ] account_move_line_report_xls
- [x] account_financial_report_webkit > account_financial_report_qweb - By @jcoux - #211 
- [x] account_financial_report_webkit_xls > account_financial_report_qweb - By @jcoux - #211 
- [ ] account_chart_report
- [x] account_financial_report_horizontal - By @hbrunn - #249 
- [x] ~~account_financial_report~~ Not maintained
- [x] ~~account_tax_report_no_zeroes~~ - Deleted as no more valid
- [ ] account_export_csv
- [x] mis_builder - By @sbidoul - #189

**Comment by ovnicraft** [comment]
Just for the record, PR related: https://github.com/OCA/account-financial-reporting/pull/211
