### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/account-financial-reporting#238]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [ ] account_chart_report
- [ ] account_export_csv - By @adrienpeiffer - #315 
- [ ] account_financial_report
- [x] account_financial_report_horizontal - By @mreficent - #341 
- [x] account_financial_report_qweb - By @adrienpeiffer - #240 
- [x] account_journal_report(_xls) - #366 
- [ ] account_move_line_report_xls
- [x] account_tax_balance - https://github.com/OCA/account-financial-reporting/pull/250
- [x] mis_builder - By @adrienpeiffer - #239 
- [x] mis_builder_demo - moved to OCA/mis-builder

**Comment by melroy89** [comment]
@pedrobaeza "account_financial_report_horizontal" can also marked as done.
It's merged.

**Comment by pedrobaeza** [comment]
Right, done!
