### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/account-financial-reporting#358]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] account_chart_report
- [ ] account_export_csv
- [x] account_financial_report_date_range - By @mreficent - #479 
- [ ] account_financial_report_horizontal
- [x] account_financial_report_qweb > account_financial_report - By @jbeficent - #367 
- [ ] account_journal_report_xls
- [ ] account_move_line_report_xls
- [x] account_tax_balance - By @pedrobaeza - #361 
- [x] customer_activity_statement - By @hveficent - #389 
- [x] customer_outstanding_statement - By @hveficent - #388

**Comment by melroy89** [comment]
account_financial_report_qweb & account_tax_balance can be checked above.

**Comment by pedrobaeza** [comment]
Noted

**Comment by aitorbouzas** [comment]
Isn't account_financial_report already migrated?

**Comment by pedrobaeza** [comment]
Well, that's the old one. A long history coming from 6.1...

I have removed it for avoiding confusions.

**Comment by fclementic2c** [comment]
I have the feeling that some modules do the same job
account_financial_report_horizontal -> Mis builder
customer_activity_statement & customer_outstanding_statement -> Open items
report in the account_financial_report

Don't you think ?



*camptocamp*

INNOVATIVE SOLUTIONS
BY OPEN SOURCE EXPERTS

*Frédéric Clementi*
Project Manager
Business Solutions

+41 21 619 10 41

www.camptocamp.com


2018-04-06 10:02 GMT+02:00 Pedro M. Baeza <notifications@github.com>:

**Comment by pedrobaeza** [comment]
account_financial_report_horizontal > @hbrunn maintains this module across versions. I don't know if they can switch to mis_builder.

customer_activity_statement & customer_outstanding_statement > @jbeficent is the promoter of this 2, and I think they are more complete, covering other parts, like sales and so on, but maybe then the repository is not the correct one.

**Comment by emagdalenaC2i** [comment]
Please, add account_financial_report_date_range #479 to the list
customer_activity_statement is merged in #389 
customer_outstanding_statement is merged in #388

**Comment by ghost** [comment]
I have detected on runbot that if the amounts are bigs, the PDF report doesn't show properly. The value doesn't fit in the box. On these fields the box doesn't adjust to the value as other fields do.
![1](https://user-images.githubusercontent.com/25029267/53100732-8ce08880-3528-11e9-86ec-fbe90bab63d0.png)

**Comment by ghost** [comment]
Hi, does anyone know anything about this last post?

**Comment by dsolanki-initos** [comment]
Hello all,
I have migrated the module account_financial_report_horizontal to v11 and here is the PR #745
