### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/account-financial-reporting#924]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [ ] account_financial_report - By @ramiadavid - #939
- [x] account_purchase_stock_report_non_billed - By @cormaza - #1184
- [x] account_sale_stock_report_non_billed - By @cormaza - #1183
- [x] account_tax_balance - By @ramiadavid - #937
- [x] mis_builder_cash_flow - By @stefan-tecnativa - #1049
- [x] mis_template_financial_report - By @hbrunn - #1144
- [ ] partner_statement - By @odooNextev - #1100

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by ramiadavid** [comment]
Hi @sbidoul 
Im working in `account_tax_balance`  #937

**Comment by ramiadavid** [comment]
Hi @sbidoul 
Im working in `account_financial_report`  #939

**Comment by dsolanki-initos** [comment]
Migrating partner_statement https://github.com/OCA/account-financial-reporting/pull/1028

**Comment by odooNextev** [comment]
Hi @sbidoul,
we're trying to migrate partner_statement
https://github.com/OCA/account-financial-reporting/pull/1100
